name: PR - Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup nuget sources
      run: dotnet nuget add source https://nuget.pkg.github.com/AdamBOD/index.json -n GPR -u AdamBOD -p GPR_TOKEN --store-password-in-clear-text
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Clean
      run: dotnet clean ./CMS.API.sln -- configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
