name: PR - Build & Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GPR_TOKEN: ${{ secrets.GPR_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1.0.2
    - name: Add GPR Source using nuget.exe
      run: nuget sources add -name "GPR" -Source https://api.nuget.org/v3/index.json -Source https://nuget.pkg.github.com/AdamBOD/index.json -Username AdamBOD -Password GPR_TOKEN
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Clean
      run: dotnet clean ./CMS.API.sln -- configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
